version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: logs.log
    formatter: extended
    

loggers:
  dev:
    handlers: [console, file_handler]
    level: INFO
    propagate: false
  test:
    handlers: [file_handler]
    level: INFO
root:
  handlers: [file_handler]